#spring.profiles.active=happy
server:
  port: 8089
spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        master:
          url: jdbc:p6spy:mysql://192.168.11.75:3306/lz-cim?serverTimezone=Asia/Shanghai
          username: root
          password: root
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 12MB
      max-request-size: 12MB
  mvc:
    dispatch-options-request: true
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml

#  spring.http.multipart.maxFileSize=10MB
#  spring.http.multipart.maxRequestSize=10MB



